### ISSUE TITLE
Validation mistake

### ISSUE THREAD

**Issue by motosumiyoshisun** [0x1-company/ios-app#357]
I inputed "_motosumiyoshi" in Bematch.
This request was successful.
But BeReal is not allowded this name.

**Comment by motosumiyoshisun** [comment]
@tomokisun

**Comment by tomokisun** [comment]
It is not possible for BeMatch to know if that username exists in BeReal.
Validation is as expected.

**Comment by motosumiyoshisun** [comment]
Wow
